import type { LucideProps } from 'lucide-react';
import {
  AlertTriangle,
  ArrowDownWideNarrow,
  ArrowRightLeft,
  BadgeDollarSign,
  BadgePercent,
  Boxes,
  Building,
  Building2,
  Cable,
  ChartColumnIncreasing,
  Crown,
  Factory,
  FileBadge,
  Folders,
  Globe2,
  Hammer,
  Landmark,
  Leaf,
  Network,
  Orbit,
  Package,
  PackageOpen,
  Scale,
  Search,
  ShieldCheck,
  Ship,
  ShipWheel,
  TrendingUp,
  Users,
  WalletCards,
  Waypoints,
  Workflow,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  AlertTriangle,
  ArrowDownWideNarrow,
  ArrowRightLeft,
  BadgeDollarSign,
  BadgePercent,
  Boxes,
  Building,
  Building2,
  Cable,
  ChartColumnIncreasing,
  Crown,
  Factory,
  FileBadge,
  Folders,
  Globe2,
  Hammer,
  Landmark,
  Leaf,
  Network,
  Orbit,
  Package,
  PackageOpen,
  Scale,
  Search,
  ShieldCheck,
  Ship,
  ShipWheel,
  TrendingUp,
  Users,
  WalletCards,
  Waypoints,
  Workflow,
};

export const IconGlyph = ({ name, ...props }: LucideProps & { name: string }) => {
  const Component = iconMap[name] ?? Building2;
  return <Component {...props} />;
};
